In [12]:
import numpy as np

In [13]:
a = np.array([[1,2,3],[2,3,4]])

In [14]:
b = a

In [15]:
for i,row in enumerate(a):
    diff = row[0]-0
    for j,col in enumerate(row):
        b[i][j] = a[i][j] - diff

In [16]:
b

array([[0, 1, 2],
       [0, 1, 2]])

In [17]:
a

array([[0, 1, 2],
       [0, 1, 2]])

In [18]:
c = np.zeros(a.shape)

In [19]:
c

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])